version: '3'
services:
  client:
    container_name: portfolio_client
    image: portfolio_client
    build:
      context: ./client
    restart: always
    depends_on:
      - strapi
    volumes:
      - ./client:/client
    command: npm run dev
    restart: always
  # END CLIENT

  nginx:
    container_name: portfolio_nginx
    image: nginx:latest
    depends_on:
      - strapi
      - client
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  strapi:
    container_name: portfolio_strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: portfolio
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_SSL: 'false'
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    restart: always
    # END STRAPI
  
  mysql:
    container_name: portfolio_mysql
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    # END MYSQL
